// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vabijlshixuatvddovle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYmlqbHNoaXh1YXR2ZGRvdmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMjYwNDUsImV4cCI6MjA1MDcwMjA0NX0.PtrOA5_lJdnSX4U1RNL8pYcGJMYhb9lN_qq11CATQGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);